### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by simplydevlish** [complexorganizations/wireguard-installer-manager#150]
I tried installing your script & it gives me this error below. How can I fix this?

> Failed to restart [wg-quick@wg0.service](mailto:wg-quick@wg0.service): Unit [wg-quick@wg0.service](mailto:wg-quick@wg0.service) not found.

https://imgur.com/dxPzX6Y

Wireguard installed on Digital Ocean droplet using Ubuntu 19.10 x64

**Comment by Prajwal-Koirala** [comment]
Did you update Linux before wireguard??

Try 2x things
1. Restart

**Comment by Prajwal-Koirala** [comment]
Hello,
Star, Sponsors, Fork, Follow is not mandatory but is much appreciated.
- Prajwal
