### ISSUE TITLE
chattr Operation not supported while reading flags on /etc/resolv.conf

### ISSUE THREAD

**Issue by bbros-dev** [complexorganizations/wireguard-installer-manager#151]
**Describe the bug**
Default headless server install errors out. Ubuntu Bionic 18.04, DigitialOcean environment.

**To Reproduce**
1. DigitalOcean
2. Launch a Droplet
3. Login to console

```bash
export HEADLESS_INSTALL=y
wireguard-server.sh
```

```bash
chattr Operation not supported while reading flags on /etc/resolv.conf
```

**Expected behavior**
Error free default installation

I believe you need to check for symlinks or mounts on tmpfs.

HTH.

**Comment by Prajwal-Koirala** [comment]
Can you make a pull?

**Comment by Prajwal-Koirala** [comment]
Fixed.

**Comment by Prajwal-Koirala** [comment]
1. Create a droplet on Digital Ocean (Ubuntu 18.04)
2. SSH Into the Droplet
3. ```wget https://raw.githubusercontent.com/complexorganizations/wireguard-installer-manager/master/wireguard-server.sh -P /etc/wireguard/```
4. ```bash -x /etc/wireguard/wireguard-client.sh >> /etc/wireguard/wireguard.log```
5. ```cat /etc/wireguard/wireguard.log```
6. Post all logs here.

**Comment by Prajwal-Koirala** [comment]
Fixed.
