### ISSUE TITLE
Ubuntu Bionic GPG key not installed for wireguard repo.

### ISSUE THREAD

**Issue by bbros-dev** [complexorganizations/wireguard-installer-manager#152]
**Describe the bug**
Default headless server install does not install package GPG key out. Ubuntu Bionic 18.04, DigitialOcean environment.

**To Reproduce**
1. DigitalOcean
2. Launch a Droplet Ubuntu 18.04
3. Login to console

```bash
export HEADLESS_INSTALL=y
wireguard-server.sh
...
GPG error: http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY AE33835F504A1A25
...
```

**Expected behavior**
Error free default server  install.

**Comment by Prajwal-Koirala** [comment]
Can you make a pull?

**Comment by Prajwal-Koirala** [comment]
unable to reproduce the same issue,

Can you please follow these instructions and post the logs.

1. Create a droplet on Digital Ocean (Ubuntu 18.04)
2. SSH Into the Droplet
3. ```wget https://raw.githubusercontent.com/complexorganizations/wireguard-installer-manager/master/wireguard-server.sh -P /etc/wireguard/```
4. ```bash -x /etc/wireguard/wireguard-client.sh >> /etc/wireguard/wireguard.log```
5. ```cat /etc/wireguard/wireguard.log```
6. Post all logs here.

**Comment by bbros-dev** [comment]
Why the log? The key `AE33835F504A1A25` is listed on the [wireguard launchpad page](https://launchpad.net/~wireguard/+archive/ubuntu/wireguard) and is not in the scripts.

**Comment by Prajwal-Koirala** [comment]
Check this out.

```
  if [ "$DISTRO" == "ubuntu" ] && ( [ "$VERSION" == "16.04" ] || [ "$VERSION" == "18.04" ] ); then
    apt-get update
    apt-get install software-properties-common -y
    add-apt-repository ppa:wireguard/wireguard -y
    apt-get update
    apt-get install linux-headers-"$(uname -r)" -y
    apt-get install wireguard qrencode haveged -y
  fi
```
https://github.com/complexorganizations/wireguard-installer-manager/blob/master/wireguard-server.sh#L409

We already install software properties
and than we add the PPA, it should add all the necessary keys already.

**Comment by bbros-dev** [comment]
No. Something weird is going on.  Standby.

**Comment by Prajwal-Koirala** [comment]
> No. Something weird is going on. Standby.

ok

**Comment by bbros-dev** [comment]
Got it.  It was a broken install for ubuntu 18.08, fixed 6 hours ago [by this commit](https://github.com/complexorganizations/wireguard-installer-manager/commit/8e44b80489ea5a669e3a649f531700d9d04408da).
