### ISSUE TITLE
Ubuntu 18.04: ifupdown2 package missing.

### ISSUE THREAD

**Issue by bbros-dev** [complexorganizations/wireguard-installer-manager#153]
**Describe the bug**
ifquery package missing - Ubuntu 18.04.

**To Reproduce**
1. DigitalOcean
2. Launch a Droplet
3. Login to console

```bash
ifquery: not found
```

**Expected behavior**
No errors from default server install script.

**Additional context**
This is a known issue [reported upstream](https://bugs.launchpad.net/ubuntu/+source/resolvconf/+bug/1782274)

**Comment by Prajwal-Koirala** [comment]
1. Create a droplet on Digital Ocean (Ubuntu 18.04)
2. SSH Into the Droplet
3. ```wget https://raw.githubusercontent.com/complexorganizations/wireguard-installer-manager/master/wireguard-server.sh -P /etc/wireguard/```
4. ```bash -x /etc/wireguard/wireguard-client.sh >> /etc/wireguard/wireguard.log```
5. ```cat /etc/wireguard/wireguard.log```
6. Post all logs here.

**Comment by bbros-dev** [comment]
Again, why dispute this? Upstream have acknowledged it is an issue - see the issue I linked to.

**Comment by Prajwal-Koirala** [comment]
> Again, why dispute this? Upstream have acknowledged it is an issue - see the issue I linked to.

I just created a droplet and tried this entire thing myself again and didn't see a single issue, it might have been with your droplet only.

Not even sure what went wrong just trying to get to the bottom of this.

**Comment by bbros-dev** [comment]
This is an acknowledged issue upstream, I experienced what upstream described. Can the package be added to the list to be installed?

**Comment by Prajwal-Koirala** [comment]
I was thinking about a final script that did everything and instead of repo we just did git clone for everything and build everything from source.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-installer-manager/pull/156

Can you try this script.

**Comment by Prajwal-Koirala** [comment]
Fixed.

**Comment by bbros-dev** [comment]
Please reopen - it's not fixed.

**Comment by Prajwal-Koirala** [comment]
When it's being complied from source it doesn't need any of this, give it a try.

**Comment by bbros-dev** [comment]
Sorry - leaving.  We're not having snowflake builds.
