### ISSUE TITLE
HEADLESS=y installs should not block waiting for input

### ISSUE THREAD

**Issue by bbros-dev** [complexorganizations/wireguard-installer-manager#154]
**Describe the bug**
execute `HEADLESS=y wireguard-server.sh` twice and the second run blocks waiting for input - see below.

**To Reproduce**
1. DigitalOcean
2. Launch a Droplet
3. Login to console

```bash
export HEADLESS_INSTALL=y
wireguard-server.sh
wireguard-server.sh
```
**Observed Behaviour**
On the second run:
```bash
   Looks like Wireguard is already installed.
   What do you want to do?
       1) Show WireGuard Interface
       2) Start WireGuard Interface
       3) Stop WireGuard Interface
       4) Add WireGuard Peer
       5) Remove WireGuard Peer
       6) Uninstall WireGuard Interface
       7) Update this script
       8) Exit
```

**Expected behavior**
Completes with no error or user input. Default setting of Option 1 is likely the least worst option here.

**Additional context**
Arguably the second run should leave the server in the same state as the install.
However, working out the divergences between runs would be near impossible.

**Workaround**
Until a fix is in place, document the workaround to have no-input required installs is:

```bash
export HEADLESS_INSTALL=y
export WIREGUARD_OPTIONS=1
wireguard-server.sh
wireguard-server.sh
```

**Comment by Prajwal-Koirala** [comment]
I'll fix this tonight.

**Comment by bbros-dev** [comment]
OK, what does that mean? 
I'm sorry this is extremely frustrating, you close issues without reference to the PR that fixes the issue.
Now I have to waste my time trawling through the code to see what you might have or might not have done.
This wasting of time is why GH introduced cross refenecing within issues and also between PRs.

Please consider using them.

**Comment by bbros-dev** [comment]
Leaving.  See Issue #153.

**Comment by Prajwal-Koirala** [comment]
Fixed.
https://github.com/complexorganizations/wireguard-manager/pull/184
